package goerrors

import (
	"errors"
)

var (
	// ErrBadRquestError ...
	ErrBadRquestError = errors.New("[E4000] Bad Request")
	// ErrNotAuthorized ...
	ErrNotAuthorized = errors.New("[E4010] Not Authorized")
	// ErrForBidden ...
	ErrForBidden = errors.New("[E4030] Forbidden")
	// ErrNotFound ...
	ErrNotFound = errors.New("[E4040] Not Found")
	// ErrRequestTimeout ...
	ErrRequestTimeout = errors.New("[E4080] Request Timeout")
	// ErrInternalServerError ...
	ErrInternalServerError = errors.New("[E5000] Internal Server Error")
	// ErrGatewayTimeout ...
	ErrGatewayTimeout = errors.New("[E5040] Gateway Timeout")
)
