// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import arguments "github.com/tanphamhaiduong/go/delta/internal/arguments"

import context "context"
import mock "github.com/stretchr/testify/mock"
import models "github.com/tanphamhaiduong/go/delta/internal/models"

// IHandler is an autogenerated mock type for the IHandler type
type IHandler struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx, params
func (_m *IHandler) Count(ctx context.Context, params arguments.CompanyCountArgs) (int64, error) {
	ret := _m.Called(ctx, params)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, arguments.CompanyCountArgs) int64); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, arguments.CompanyCountArgs) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, params
func (_m *IHandler) Delete(ctx context.Context, params arguments.CompanyDeleteArgs) (int64, error) {
	ret := _m.Called(ctx, params)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, arguments.CompanyDeleteArgs) int64); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, arguments.CompanyDeleteArgs) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, params
func (_m *IHandler) GetByID(ctx context.Context, params arguments.CompanyGetByIDArgs) (models.Company, error) {
	ret := _m.Called(ctx, params)

	var r0 models.Company
	if rf, ok := ret.Get(0).(func(context.Context, arguments.CompanyGetByIDArgs) models.Company); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(models.Company)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, arguments.CompanyGetByIDArgs) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDs provides a mock function with given fields: ctx, params
func (_m *IHandler) GetByIDs(ctx context.Context, params arguments.CompanyGetByIDsArgs) ([]models.Company, error) {
	ret := _m.Called(ctx, params)

	var r0 []models.Company
	if rf, ok := ret.Get(0).(func(context.Context, arguments.CompanyGetByIDsArgs) []models.Company); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Company)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, arguments.CompanyGetByIDsArgs) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, params
func (_m *IHandler) Insert(ctx context.Context, params arguments.CompanyInsertArgs) (models.Company, error) {
	ret := _m.Called(ctx, params)

	var r0 models.Company
	if rf, ok := ret.Get(0).(func(context.Context, arguments.CompanyInsertArgs) models.Company); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(models.Company)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, arguments.CompanyInsertArgs) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, params
func (_m *IHandler) List(ctx context.Context, params arguments.CompanyListArgs) ([]models.Company, error) {
	ret := _m.Called(ctx, params)

	var r0 []models.Company
	if rf, ok := ret.Get(0).(func(context.Context, arguments.CompanyListArgs) []models.Company); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Company)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, arguments.CompanyListArgs) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, params
func (_m *IHandler) Update(ctx context.Context, params arguments.CompanyUpdateArgs) (models.Company, error) {
	ret := _m.Called(ctx, params)

	var r0 models.Company
	if rf, ok := ret.Get(0).(func(context.Context, arguments.CompanyUpdateArgs) models.Company); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(models.Company)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, arguments.CompanyUpdateArgs) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
