// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import arguments "github.com/tanphamhaiduong/go/delta/server/arguments"
import context "context"
import mock "github.com/stretchr/testify/mock"
import models "github.com/tanphamhaiduong/go/delta/server/models"

// IHandler is an autogenerated mock type for the IHandler type
type IHandler struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx, params
func (_m *IHandler) Count(ctx context.Context, params arguments.RoleCountArgs) (int64, error) {
	ret := _m.Called(ctx, params)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, arguments.RoleCountArgs) int64); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, arguments.RoleCountArgs) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, params
func (_m *IHandler) Delete(ctx context.Context, params arguments.RoleDeleteArgs) (int64, error) {
	ret := _m.Called(ctx, params)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, arguments.RoleDeleteArgs) int64); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, arguments.RoleDeleteArgs) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, params
func (_m *IHandler) GetByID(ctx context.Context, params arguments.RoleGetByIDArgs) (models.Role, error) {
	ret := _m.Called(ctx, params)

	var r0 models.Role
	if rf, ok := ret.Get(0).(func(context.Context, arguments.RoleGetByIDArgs) models.Role); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(models.Role)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, arguments.RoleGetByIDArgs) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDs provides a mock function with given fields: ctx, params
func (_m *IHandler) GetByIDs(ctx context.Context, params arguments.RoleGetByIDsArgs) ([]models.Role, error) {
	ret := _m.Called(ctx, params)

	var r0 []models.Role
	if rf, ok := ret.Get(0).(func(context.Context, arguments.RoleGetByIDsArgs) []models.Role); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Role)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, arguments.RoleGetByIDsArgs) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, params
func (_m *IHandler) Insert(ctx context.Context, params arguments.RoleInsertArgs) (models.Role, error) {
	ret := _m.Called(ctx, params)

	var r0 models.Role
	if rf, ok := ret.Get(0).(func(context.Context, arguments.RoleInsertArgs) models.Role); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(models.Role)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, arguments.RoleInsertArgs) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, params
func (_m *IHandler) List(ctx context.Context, params arguments.RoleListArgs) ([]models.Role, error) {
	ret := _m.Called(ctx, params)

	var r0 []models.Role
	if rf, ok := ret.Get(0).(func(context.Context, arguments.RoleListArgs) []models.Role); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Role)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, arguments.RoleListArgs) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, params
func (_m *IHandler) Update(ctx context.Context, params arguments.RoleUpdateArgs) (models.Role, error) {
	ret := _m.Called(ctx, params)

	var r0 models.Role
	if rf, ok := ret.Get(0).(func(context.Context, arguments.RoleUpdateArgs) models.Role); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(models.Role)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, arguments.RoleUpdateArgs) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
