package graphqltype

const (
	// Int ...
	Int = "graphql.Int"
	// String ...
	String = "graphql.String"
	// DateTime ...
	DateTime = "graphql.DateTime"
	// Boolean ...
	Boolean = "graphql.Boolean"
	// Float ...
	Float = "graphql.Float"
	// NullDateTime ...
	NullDateTime = "customgraphql.NullDateTime"
)
